### ISSUE TITLE
kafkactl get consumer-groups fails

### ISSUE THREAD

**Issue by tarys** [deviceinsight/kafkactl#109]
Error message:
`failed to get group member assignment: kafka: insufficient data to decode packet, more bytes expected`

All other commands work just fine.

kafkactl version:
`cmd.info{version:"v1.23.1", buildTime:"2021-11-23T13:08:18Z", gitCommit:"9cb9f72", goVersion:"go1.16.10", compiler:"gc", platform:"darwin/amd64"}`

**Comment by random-dwi** [comment]
Hey @tarys,
which kafka version has your cluster?
did you specify a kafka version in your config?

**Comment by tarys** [comment]
1. Kafka version: `2.7.0`
2. `~/.config/kafkactl/config.yml`:
    ```yaml
    contexts:
      dev-cluster:
        brokers:
        - dev-cluster:9091
        kafkaVersion: 2.7.0
    current-context: dev-cluster
    ```

Port `9091` is configured for PLAINTEXT protocol, no authentication/authorization.
