### ISSUE TITLE
Allow changing the container image for Kubernetes environments

### ISSUE THREAD

**Issue by fahlke** [deviceinsight/kafkactl#116]
Hi!

I some / many Kubernetes environments it is required to use a specific registry and secrets to pull container images, for various reasons. Also one could rapidly run into the Docker Hub rate limit (anonymous: 100 pulls per 6 hours) when extensively using kafkactl in Kubernetes.

It would greatly enhance the user experience and enable more people to use it, if it would be possible to adjust the container image location and also add Kubernetes imagePullSecrets.

Currently it is not possible from what I saw in [executor.go#L109](https://github.com/deviceinsight/kafkactl/blob/main/internal/k8s/executor.go#L109) to change the image at all, as it is hard-coded.

Proposal:
- add an optional parameter to configure the container image, tag and image type in `config.yml` in the kubernetes section
- add an optional parameter to configure the image pull secret in `config.yml` in the kubernetes section

Example:
```yaml
...
contexts:
  ...
  remote-cluster:
    ...
    kubernetes:
      ...
      image: registry.example.com/deviceinsight/kafkactl:v2.0.1-scratch #optional
      imagePullSecret: registry-secret #optional
...
```
