### ISSUE TITLE
Docker: BROKERS env variable interferes with config file

### ISSUE THREAD

**Issue by retoo** [deviceinsight/kafkactl#138]
When trying to configure a kafka-console pod (using your docker image) on our cluster, we were wondering why our configurations wouldn't take any effect. 

Turns out, the Dockerfile defines `BROKERS=localhost:9092`which overrides any manual configuration.

Would it be possible to remove that ENV statement from the Dockerfile? 

Workaround within the pod template is to just unset the variable:

```yaml
env:
  - name: BROKERS # we unset the default value, as it overrides our config map
    value: ""
```

My kubernetes definition:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-console
spec:
  selector:
    matchLabels:
      name: kafka-console
  replicas: 1
  serviceName: kafka-console
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: kafka-console
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: kafka-console
          image: deviceinsight/kafkactl:latest
          command: [ "/bin/sh" ]
          args: [ "-c", "trap : TERM INT; sleep 365d & wait" ]
          env:
            - name: BROKERS
              value: ''
          volumeMounts:
            - mountPath: /home/kafkactl/.config/kafkactl/
              name: kafka-console-config
      volumes:
        - name: kafka-console-config
          configMap:
            name: kafka-console
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-console
data:
  config.yml: |+
    contexts:
      default:
        brokers:
          - my-kafka-0:9202
          - my-kafka-1:9202
          - my-kafka-2:9202
    current-context: default
```
