### ISSUE TITLE
Connecting with TLS-certificates from Strimzi Kafka Operator

### ISSUE THREAD

**Issue by arve0** [deviceinsight/kafkactl#157]
Hi! Thanks for the tool 👍

I'm unable to connect when using certificates generated by [Strimzi](https://strimzi.io), which works with shell tools provided by kafka (for example kafka-producer-perf-test.sh).

This is my setup:

```yaml
contexts:
  default:
    brokers:
      - localhost:9094

    tls:
      enabled: true
      ca: /Users/arve/.config/kafkactl/ca.crt
      cert: /Users/arve/.config/kafkactl/user.crt
      key: /Users/arve/.config/kafkactl/user.key
      insecure: true

    kafkaVersion: 3.4.0

current-context: default
```

Output from kafkactl:
```
❯ kafkactl describe broker 0 -V
[kafkactl] 2023/08/18 14:36:43 Using config file: /Users/arve/.config/kafkactl/config.yml
[kafkactl] 2023/08/18 14:36:43 Using kafkaVersion: 3.4.0
[kafkactl] 2023/08/18 14:36:43 Using kafkaVersion: 3.4.0
[kafkactl] 2023/08/18 14:36:43 using default admin request timeout: 3s
[kafkactl] 2023/08/18 14:36:43 TLS is enabled.
[sarama  ] 2023/08/18 14:36:43 Initializing new client
[sarama  ] 2023/08/18 14:36:43 client/metadata fetching metadata for all topics from broker localhost:9094
[sarama  ] 2023/08/18 14:36:43 Connected to broker at localhost:9094 (unregistered)
[sarama  ] 2023/08/18 14:36:43 client/metadata got error from broker -1 while fetching metadata: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:43 Closed connection to broker localhost:9094
[sarama  ] 2023/08/18 14:36:43 Error while sending ApiVersionsRequest to broker localhost:9094: kafka: broker not connected
[sarama  ] 2023/08/18 14:36:43 client/metadata no available broker to send metadata request to
[sarama  ] 2023/08/18 14:36:43 client/brokers resurrecting 1 dead seed brokers
[sarama  ] 2023/08/18 14:36:43 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama  ] 2023/08/18 14:36:43 client/metadata fetching metadata for all topics from broker localhost:9094
[sarama  ] 2023/08/18 14:36:43 Connected to broker at localhost:9094 (unregistered)
[sarama  ] 2023/08/18 14:36:44 Error while sending ApiVersionsRequest to broker localhost:9094: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:44 client/metadata got error from broker -1 while fetching metadata: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:44 Closed connection to broker localhost:9094
[sarama  ] 2023/08/18 14:36:44 client/metadata no available broker to send metadata request to
[sarama  ] 2023/08/18 14:36:44 client/brokers resurrecting 1 dead seed brokers
[sarama  ] 2023/08/18 14:36:44 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama  ] 2023/08/18 14:36:44 client/metadata fetching metadata for all topics from broker localhost:9094
[sarama  ] 2023/08/18 14:36:44 Connected to broker at localhost:9094 (unregistered)
[sarama  ] 2023/08/18 14:36:44 client/metadata got error from broker -1 while fetching metadata: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:44 Error while sending ApiVersionsRequest to broker localhost:9094: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:44 Closed connection to broker localhost:9094
[sarama  ] 2023/08/18 14:36:44 client/metadata no available broker to send metadata request to
[sarama  ] 2023/08/18 14:36:44 client/brokers resurrecting 1 dead seed brokers
[sarama  ] 2023/08/18 14:36:44 client/metadata retrying after 250ms... (0 attempts remaining)
[sarama  ] 2023/08/18 14:36:44 client/metadata fetching metadata for all topics from broker localhost:9094
[sarama  ] 2023/08/18 14:36:45 Connected to broker at localhost:9094 (unregistered)
[sarama  ] 2023/08/18 14:36:45 Error while sending ApiVersionsRequest to broker localhost:9094: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:45 client/metadata got error from broker -1 while fetching metadata: remote error: tls: bad certificate
[sarama  ] 2023/08/18 14:36:45 Closed connection to broker localhost:9094
[sarama  ] 2023/08/18 14:36:45 client/metadata no available broker to send metadata request to
[sarama  ] 2023/08/18 14:36:45 client/brokers resurrecting 1 dead seed brokers
[sarama  ] 2023/08/18 14:36:45 Closing Client
failed to create client: kafka: client has run out of available brokers to talk to: remote error: tls: bad certificate
```

localhost:9094 is portforwarded to kafka service with `oc port-forward svc/kafka-kafka-0 9094:9094`.

`KafkaUser` which creates certificates:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: kafka
    strimzi.io/cluster: kafka
  name: kafka-ui
  namespace: kafka
spec:
  authentication:
    type: tls
  authorization:
    acls:
    - operations:
      - Read
      - Describe
      resource:
        name: '*'
        type: cluster
    - operations:
      - Read
      - Describe
      resource:
        name: '*'
        type: topic
    - operations:
      - Read
      - Describe
      resource:
        name: '*'
        type: group
    - operations:
      - Read
      - Describe
      resource:
        name: '*'
        type: transactionalId
    type: simple
```

Got certificates from `Secret`:
```sh
oc get secret kafka-cluster-ca-cert -o yaml | yq '.data."ca.crt"' | base64 -d > ~/.config/kafkactl/ca.crt
oc get secret kafka-ui -o yaml | yq '.data."user.crt"' | base64 -d > ~/.config/kafkactl/user.crt
oc get secret kafka-ui -o yaml | yq '.data."user.key"' | base64 -d > ~/.config/kafkactl/user.key
```

Any ideas what I'm doing wrong?
