### ISSUE TITLE
Default config generation

### ISSUE THREAD

**Issue by dwi-di** [deviceinsight/kafkactl#22]
In order to simplify getting started with kafkactl we should try to generate a simple config file automatically if no config was found.
This config should work for a kafka cluster running locally on localhost:9092 so it should look like this:

```
contexts:
  localhost:
    brokers:
    - localhost:9092
current-context: localhost
```
for the config file location we should use `$HOME/.config/kafkactl/config.yml` (location according to XDG)
