### ISSUE TITLE
Has of today release v5.6.0 avro message are not properly produce

### ISSUE THREAD

**Issue by pmpinson** [deviceinsight/kafkactl#241]
We are using kafkactl within the docker wrapper deviceinsight/kafkactl to produce test data in our preprod environment.

kafka version: 2.8
schema registry 5.2.2

We are using kafka-schema registry and have not change the way we produce messages.
We are doing a docker pull of the latest version before we start producing messages.

Yesterday we started to have some consumers complaining that they cannot read messages with an exception during dezerialization of avro message.

The message is produced into kafka but the schema id is not valid so we cannot deserialize the message

here the error message from kafkactl when consuming invalid message (installed on mac with homebrew), id 577073257 does not exist, our last id is 1732 
````
Error during deserialization: failed to find avro schema for subject: sessions-value id: 577073257 ({"error_code":40403,"message":"Schema not found"})
````

from kowl ui tool here metadata of a message produced with v5.6.0
<img width="702" alt="Image" src="https://github.com/user-attachments/assets/dfa89f39-24f0-421d-8dd9-e7596f056de2" />

from kowl ui tool here metadata of the same message produced with v5.5.1
<img width="748" alt="Image" src="https://github.com/user-attachments/assets/73414adf-c39e-4cd6-8dea-c0f192b8f460" />

command line used to produce message
```
docker run -v /config/kafkactl-config-preprod-fakedata.yml:/etc/kafkactl/config.yml -v /data/messages.json:/data/messages.json deviceinsight/kafkactl produce sessions --separator=# --file=/data/messages.json
```

here the schema registry config file
```
preprod:
    avro:
      schemaregistry: http://preprod-registry.ourdomain.net:8081
    brokers:
    - preprod-kaf01.ourdomain.net:9092
    - preprod-kaf02.ourdomain.net:9092
    - preprod-kaf03.ourdomain.net:9092
    clientid: preprod-fakedata-kafkactl
    defaultpartitioner: hash
    kafkaversion: 1.1.1
```

here a sample of /messages.json where do some sed to replace fakecurrentDateTimeToReplace
````
4801_3e2c63dd-313c-492e-a2f4-02b338b7dbea_fakecurrentDateTimeToReplace#{"id":"121262-_fakecurrentDateTimeToReplace","session_duration":4, "start":fakecurrentDateTimeToReplace}
```

**Comment by d-rk** [comment]
Hey @pmpinson 

we changed the schemaRegistry config, because the the schema registry can also hold protobuf schemas and in the future we want to be able deserialize them as well.

So, the config changed slightly. Can you check if a change in your config resolved the issue?

```
preprod:
    schemaRegistry:
      url: http://preprod-registry.ourdomain.net:8081
    brokers:
    - preprod-kaf01.ourdomain.net:9092
    - preprod-kaf02.ourdomain.net:9092
    - preprod-kaf03.ourdomain.net:9092
    clientid: preprod-fakedata-kafkactl
    defaultpartitioner: hash
    kafkaversion: 1.1.1
```
