### ISSUE TITLE
Context switch alters dot-containing keys in YAML configuration

### ISSUE THREAD

**Issue by mwalser** [deviceinsight/kafkactl#268]
#### Description
After executing the command `kafkactl config use-context my-context`, the YAML configuration in `config.yml` is altered in an undesired way. Specifically, configuration keys containing dots (`.`) are transformed into nested structures. This behavior affects keys intended as Kubernetes labels.

#### Steps to Reproduce
1. Create a `config.yml` file with the following structure:
   ```yaml
   contexts:
       my-context:
           brokers:
               - xxx.servicebus.windows.net:9093
           kubernetes:
               enabled: true
               image: deviceinsight/kafkactl-azure:latest-v5.9.0
               kubecontext: my-cluster
               labels:
                   "azure.workload.identity/use": "true"
               namespace: default
               serviceaccount: my-serviceaccount
           sasl:
               enabled: true
               mechanism: oauth
               tokenprovider:
                   plugin: azure
           tls:
               enabled: true
   current-context: my-context
   ```
2. Run the command:
   ```bash
   kafkactl config use-context my-context
   ```
3. Observe the transformation in the `config.yml` file.

#### Expected Behavior
The configuration keys containing dots should remain unchanged, preserving their original format:
```yaml
labels:
    "azure.workload.identity/use": "true"
```

#### Actual Behavior
The configuration keys containing dots are transformed into nested structures:
```yaml
labels:
    azure:
        workload:
            identity/use: "true"
```

#### Version used
```
❯ kafkactl version
cmd.info{version:"v5.9.0", buildTime:"2025-06-16T08:17:46Z", gitCommit:"248f075", goVersion:"go1.24.4", compiler:"gc", platform:"linux/amd64"}
```
