### ISSUE TITLE
Custom CA cert in 1.8 

### ISSUE THREAD

**Issue by ateijelo** [deviceinsight/kafkactl#46]
I'm having the opposite issue in 1.8.0 to the one addressed by https://github.com/deviceinsight/kafkactl/pull/41.

I have a config file with two contexts, one using AWS's MSK, with the CA cert omitted, and the other one using a local cluster with TLS enabled, which uses a custom CA cert:

```
contexts:

  emma-client-1:
    brokers:
    - b1.kafka.emma:9091
    - b2.kafka.emma:9092

    tls:
      enabled: true
      # insecure: true
      ca: /home/ateijelo/.config/kafka/emma-caroot.pem
      cert: /home/ateijelo/.config/kafka/emma-client-1-cert.pem
      certkey: /home/ateijelo/.config/kafka/emma-client-1-key.pem

    #tlsCA: /home/ateijelo/.config/kafka/emma-caroot.pem
    #tlsCert: /home/ateijelo/.config/kafka/emma-client-1-cert.pem
    #tlsCertKey: /home/ateijelo/.config/kafka/emma-client-1-key.pem

  msk-client-1:
    brokers:
    - b-1....my-msk-cluster....amazonaws.com:9094
    - b-2....my-msk-cluster....amazonaws.com:9094
    tls:
      enabled: true
      cert: /home/ateijelo/.config/kafka/msk-client-1-cert.pem
      certKey: /home/ateijelo/.config/kafka/msk-client-1-key.pem
```

Using 1.7.0 with the deprecated `tlsCA`, `tlsCert`, `tlsCertKey` works fine with both MSK and my local cluster.
Using 1.8.0 with the new `tls` block works fine with MSK, but not with the local cluster, I get:

```
failed to create cluster admin: kafka: client has run out of available brokers 
to talk to (Is your cluster reachable?)
```
